CREATE TABLE "accounts" (
  "account_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner" varchar NOT NULL UNIQUE,
  "balance" real NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "services" (
  "service_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "products" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "price" real NOT NULL,
  "amount" int NOT NULL
);

CREATE TABLE "transfers" (
  "transfer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "service_id" int NOT NULL,
  "total_price" real NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "description" varchar NOT NULL,
  "status" varchar NOT NULL
);

CREATE TABLE "ordersDetails" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transfer_id" int NOT NULL,
  "product_id" int NOT NULL,
  "amount" int NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

ALTER TABLE "transfers" ADD FOREIGN KEY ("user_id") REFERENCES "accounts" ("account_id");

ALTER TABLE "transfers" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("service_id");

ALTER TABLE "ordersDetails" ADD FOREIGN KEY ("transfer_id") REFERENCES "transfers" ("transfer_id");

ALTER TABLE "ordersDetails" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");



INSERT INTO "services" ("name") VALUES('Buy');
INSERT INTO "services" ("name") VALUES('Sell');


INSERT INTO "products" ("name", "price", "amount") VALUES('TV', 120.0, 35);
INSERT INTO "products" ("name", "price", "amount") VALUES('Xbox', 570.0, 10);
INSERT INTO "products" ("name", "price", "amount") VALUES('Keyboard', 12.0, 5);
INSERT INTO "products" ("name", "price", "amount") VALUES('X-pad', 52.0, 1);
INSERT INTO "products" ("name", "price", "amount") VALUES('Clock', 22.0, 25);
