CREATE TABLE "accounts" (
  "account_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner" varchar,
  "balance" numeric,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "services" (
  "service_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "products" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "price" numeric,
  "amount" int
);

CREATE TABLE "transfers" (
  "transfer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "service_id" int,
  "total_price" numeric,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "ordersDetails" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transfer_id" int,
  "product_id" int,
  "amount" int,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

ALTER TABLE "transfers" ADD FOREIGN KEY ("user_id") REFERENCES "accounts" ("account_id");

ALTER TABLE "transfers" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("service_id");

ALTER TABLE "ordersDetails" ADD FOREIGN KEY ("transfer_id") REFERENCES "transfers" ("transfer_id");

ALTER TABLE "ordersDetails" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");
